# Generated by Django 3.0.5 on 2020-04-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('first_picture', models.ImageField(upload_to='static/images/')),
                ('second_picture', models.ImageField(upload_to='static/images/')),
                ('third_picture', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='lastprojects',
            options={'verbose_name': 'Последний проэкт', 'verbose_name_plural': 'Последние проэкты'},
        ),
        migrations.AlterField(
            model_name='lastprojects',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lastprojects',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
