# Generated by Django 3.0.5 on 2020-04-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200429_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselevel',
            name='title',
            field=models.CharField(default='ti', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baselevel',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
