# Generated by Django 3.0.5 on 2020-04-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200430_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='baselevel',
            name='description',
            field=models.TextField(help_text='Возможно ввести только до 400 символов', max_length=400, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='baselevel',
            name='first_picture',
            field=models.ImageField(upload_to='static/images/', verbose_name='фотография 1'),
        ),
        migrations.AlterField(
            model_name='baselevel',
            name='second_picture',
            field=models.ImageField(upload_to='static/images/', verbose_name='фотография 2'),
        ),
        migrations.AlterField(
            model_name='baselevel',
            name='third_picture',
            field=models.ImageField(upload_to='static/images/', verbose_name='фотография 3'),
        ),
        migrations.AlterField(
            model_name='baselevel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название 2 '),
        ),
    ]
