# Generated by Django 3.0.5 on 2020-04-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200430_0630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ans',
        ),
    ]
