# Generated by Django 3.0.5 on 2020-04-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=35, verbose_name='Страна')),
                ('city', models.CharField(max_length=35, verbose_name='город')),
                ('index', models.CharField(max_length=35, verbose_name='индекс')),
                ('street', models.CharField(max_length=35, verbose_name='улица')),
            ],
            options={
                'verbose_name': 'Местоположение',
            },
        ),
    ]
