# Generated by Django 3.0.5 on 2020-04-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200430_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
