# Generated by Django 3.0.5 on 2020-04-30 09:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='электронная почта')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакт',
            },
        ),
    ]
