# Generated by Django 3.0.5 on 2020-04-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200430_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselevel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
