# Generated by Django 3.0.5 on 2020-05-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200430_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastprojects',
            name='img',
            field=models.ImageField(upload_to='static/images/last_projecs'),
        ),
        migrations.AlterField(
            model_name='lastprojects',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
