# Generated by Django 3.0.5 on 2020-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200507_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastprojects',
            name='slug',
            field=models.SlugField(default='aa', verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baselevel',
            name='first_picture',
            field=models.ImageField(upload_to='static/images/base_level/', verbose_name='фотография 1'),
        ),
        migrations.AlterField(
            model_name='baselevel',
            name='second_picture',
            field=models.ImageField(upload_to='static/images/base_level/', verbose_name='фотография 2'),
        ),
        migrations.AlterField(
            model_name='baselevel',
            name='third_picture',
            field=models.ImageField(upload_to='static/images/base_level/', verbose_name='фотография 3'),
        ),
        migrations.AlterField(
            model_name='lastprojects',
            name='img',
            field=models.ImageField(upload_to='static/images/last_projecs/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='lastprojects',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
