# Generated by Django 3.0.5 on 2020-05-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200512_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastprojects',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Ссылка'),
        ),
    ]
