# Generated by Django 3.0.5 on 2020-05-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200512_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=100, verbose_name='Под пункт')),
            ],
        ),
        migrations.RemoveField(
            model_name='baselevel',
            name='description',
        ),
    ]
