# Generated by Django 3.0.5 on 2020-05-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200512_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baselevel',
            options={'verbose_name': 'Правая панель', 'verbose_name_plural': 'Правая панель'},
        ),
    ]
