# Generated by Django 3.0.5 on 2020-05-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200512_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('question', models.TextField(max_length=300, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопросиник',
                'verbose_name_plural': 'Вопросники',
            },
        ),
    ]
