# Generated by Django 3.0.5 on 2020-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_askquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselevel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название 2'),
        ),
    ]
