# Generated by Django 3.0.5 on 2020-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200519_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselevel',
            name='description',
            field=models.TextField(default='aaaaaaaaaaaaaa', verbose_name='Описание про нас'),
            preserve_default=False,
        ),
    ]
