# Generated by Django 3.0.5 on 2020-05-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='lastprojects',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
